### ISSUE TITLE
handle Nones when sending messages

### ISSUE THREAD

**Issue by cristihainic** [cristihainic/telegram-proxy-bot#17]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sanic/app.py", line 724, in handle_request
    response = await response
  File "/proxybot/bot/controllers.py", line 58, in updates
    if 'send' in txt:
TypeError: argument of type 'NoneType' is not iterable

**Comment by cristihainic** [comment]
solvable by checking for the existence of `txt`:
```
if chat_id == proxy_to and txt:
```

**Comment by cristihainic** [comment]
fixing soon!
